services:
  backend:
    ports:
      - "4000:4000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    ports:
      - "5173:5173"
    build:
      context: ./website
      dockerfile: Dockerfile
    volumes:
      - ./website:/app
      - frontend_node_modules:/app/node_modules

  rag:
    ports:
      - "8000:8000"
    build:
      context: ./RAG
      dockerfile: Dockerfile
    volumes:
      - ./RAG:/app
      - ./RAG/uploaded_docs:/uploaded_docs
    depends_on:
      - document_loader
    env_file:
      - .env

  document_loader:
    build:
      context: ./RAG/document_loader
      dockerfile: Dockerfile
    volumes:
      - ./RAG/uploaded_docs:/uploaded_docs
    env_file:
      - .env

volumes:
  backend_node_modules:
  frontend_node_modules: